version: 2.1

workflows:
  version: 2

  workflow:
    jobs:
      - Test

executors:
  tmate-fail:
    docker:
      - image: infinisil/nixpkgs-nixos-unstable:1dc37370c489b610f8b91d7fdd40633163ffbafd
    shell: bash-tmate -eo pipefail

jobs:

  Test:
    executor: tmate-fail
    steps:
      - run:
          name: Test
          command: "false"
