version: 2.1

workflows:
  version: 2

  workflow:
    jobs:
      - Test

jobs:

  Test:
    docker:
      - image: niteo/nixpkgs-nixos-20.03:504f993df9a5ca63317fe9c859df19daad30aa14
    steps:
      - run:
          name: Test
          command: nix-shell -p hello --run hello
